### ISSUE TITLE
Table query not possible, if database table row is lowercase!

### ISSUE THREAD

**Issue by Sub-Zero-1** [Azure/azure-mobile-apps-quickstarts#129]
Following situation. I am using Android and a C# Backend. I query my mobile service table with following query:

My table:

Id, orderid, name, street, city, postal, country

new AsyncTask<Void, Void, Void>() {
    @Override
    protected Void doInBackground(Void... params) {
        try {
            final MobileServiceList<order> result =
                    my_table.where().startsWith("Id",9).execute().get();
This gives me a result and everything works fine.

Backend shows me following:

Response, Status=200 (OK), Method=GET, Url=https://blaaaaaa/tables/order?$filter=startswith(Id,'9')

Now, I just try to query another item like orderid:

new AsyncTask<Void, Void, Void>() {
    @Override
    protected Void doInBackground(Void... params) {
        try {
            final MobileServiceList<order> result = my_table.where().startsWith("orderid",1234).execute().get();
This results in an error!

Backend shows me following:

Response, Status=400 (BadRequest), Method=GET, Url=https://blaaaaaaaa/tables/order?$filter=startswith(Orderid,'1234')

It seems to be the case, that the query for "orderid" is automatically transformed into "Orderid" and that is why it returns an error. So that means all table row names must start with uppercase letter?! Why?!

**Comment by clpolet** [comment]
Hi @Sub-Zero-1, I don't think table columns should all start with uppercase. There should be something else. We'll try to repo and get back at you.

**Comment by clpolet** [comment]
So the column names are case insensitive. The server may format his answer in a specific way but it shouldn't matter. Let's find the root cause of the issue in the server logs, there should be more details about the 400 there. To activate the logging server side please follow[ this App Service documentation.](https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs#enablediag)
