### ISSUE TITLE
Android: quickstart refresh all items

### ISSUE THREAD

**Issue by ProfFatimaPereira** [Azure/azure-mobile-apps-quickstarts#135]
Hi,

I created an Easy Table called ToDoItem and  I run the quickstart mobile app in Android Studio

The app seems to be working OK  with Azure Easy Table, except for the fact that does not filter any data when I try to query data from the table. 

It seems the where clause is simple ignored even though I've data in the Easy table with rows set to true in field completed .

Any idea? Is it necessary to edit the script of the easy tables in azure?

return mToDoTable.where().field("complete").
                eq(val(false)).execute().get();

Thank you in advance.

Fátima Pereira

**Comment by clpolet** [comment]
Hi @ProfFatimaPereira, thanks for reaching out. So in the [API doc](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-android-how-to-use-client-library#filtering) there is no `val()` would that solve the issue:
```
List<ToDoItem> result = mToDoTable
    .where()
    .field("complete").eq(false)
    .execute()
    .get();
```

**Comment by MatkovIvan** [comment]
Hi @ProfFatimaPereira,
we haven't heard from you in a while so I'm closing this issue.
Feel free to reopen this issue if it isn't resolved or you have additional questions.
