### ISSUE TITLE
.NET Core & Cosmos DB backend service samples?

### ISSUE THREAD

**Issue by jjgriff93** [Azure/azure-mobile-apps-quickstarts#136]
Would be really helpful to have a .NET Core sample, and one that utilises Cosmos DB instead of SQL as a backend

**Comment by elamalani** [comment]
@jjgriff93 Hi there, we are not doing active development in Azure Mobile Apps. Please refer to this [Readme](https://github.com/Azure/azure-mobile-apps#future-of-azure-mobile-apps) section. 

[App Center](appcenter.ms) is the next generation solution for Azure Mobile Apps and it supports [Data service](https://docs.microsoft.com/en-us/appcenter/data/) which is built on top of CosmosDB. You can easily onboard to App Center Data service for mobile apps. Check out the [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap#data) for the Data service. Let me know if you have any other questions. Thanks!
