### ISSUE TITLE
ZUMOAPPNAMEService can't build

### ISSUE THREAD

**Issue by yourera** [Azure/azure-mobile-apps-quickstarts#137]
Quick start example in description

It doesn't even build

Error description :
ZUMOAPPNAMEService: The path and / or file name you specified is too long. The fully qualified file name must be less than 260 characters and the directory name must be less than 248 characters. Failed to restore NuGet package for project.

**Comment by AnastasiaKubova** [comment]
Hi @yourera ! Thanks for contacting us. Looks like the problem not related to our SDK. The cause problem in [limiting the length path](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation) in Windows. You can try to change the path to the folder or you can remove the limiting the path length [here](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation)

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.
