### ISSUE TITLE
zumoappname - sync failed [android studio 3.5.3]

### ISSUE THREAD

**Issue by PoliPlanta** [Azure/azure-mobile-apps-quickstarts#144]
Hallo every one.

I try open and sync the app exemple:

azure-mobile-apps-quickstarts\client\android\ZUMOAPPNAME\app

But the sync proccess failed with one error.

"ERROR: Could not find method implementation() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler."

Someone can help me?

TKS

**Comment by Jamminroot** [comment]
Hello, @PoliPlanta, can you elaborate - at what step do you face the problem?
What steps would reproduce the problem? Did you run through and followed instructions from [this guide](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-android-get-started)?
Looking forward to hear from you

**Comment by Jamminroot** [comment]
We haven't heard from you for a while, so I'm closing the issue. Face you the problem again - please respond in this thread.
Have a nice day.
