### ISSUE TITLE
Windows UWP getting error 

### ISSUE THREAD

**Issue by jjindrich** [Azure/azure-mobile-apps-quickstarts#146]
I'm following this guide Xamarin.Forms and trying to run Windows UWP https://docs.microsoft.com/en-us/previous-versions/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-offline-data

But when I call MobileServiceSQLiteStore in Windows UWP I'm getting this exception:
Method not found: 'System.String SQLitePCL.raw.sqlite3_errstr(Int32)

When I run Android project, everything runs correctly

**Comment by AnastasiaKubova** [comment]
Hi, @jjindrich ! Thanks for getting in touch with us!
Could you please clarify what the version of sql you use?

**Comment by jjindrich** [comment]
I use as described in article https://sqlite.org/2016/sqlite-uwp-3120200.vsix version 3.12.2.

**Comment by russelarms** [comment]
@jjindrich can you try to test it with an app from [our quickstarts](https://github.com/Azure/azure-mobile-apps-quickstarts/tree/master/client/xamarin.forms)?
I've tried it and offline mode worked fine for me.

**Comment by jjindrich** [comment]
There is something strange. In quickstart project Xamarin.Forms is works. In my project it doesn't works (I took TodoList to my project). I have same version of packages :(

**Comment by jjindrich** [comment]
I spent long time on comparing, the result is clear. If you add new package Microsoft.AppCenter.Analytics into ZUMOAPPNAME project, you will get error: Method not found: 'System.String SQLitePCL.raw.sqlite3_errstr(Int32)
@russelarms can you try it to replicate ?

**Comment by AnastasiaKubova** [comment]
@jjindrich , App Center 3.0 uses SQLitePCLRaw v2 and not compatible with libraries that uses v1. For now, you can stay on 2.x to use these libraries together.

We already have [feature request](https://github.com/Azure/azure-mobile-apps-net-client/issues/533) for updating SQLitePCLRaw in Microsoft.Azure.Mobile.Client.SQLiteStore.

**Comment by jjindrich** [comment]
Ok, I will wait for #533
