### ISSUE TITLE
iOS quickstart displays splash page with title "ZUMOAPPNAME"

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-quickstarts#21]
Tested in simulator on iOS 6 Plus, Xcode 7.1.1

**Comment by danderson00** [comment]
Token exists in Launch Screen.storyboard that is not being replaced

**Comment by shrishrirang** [comment]
We should also grep for all ZUMO* strings in the downloaded quickstart folder to make sure we haven't missed anything else.

On Jan 25, 2016 6:02 PM, Dale Anderson <notifications@github.com> wrote:

Token exists in Launch Screen.storyboard that is not being replaced

-

**Comment by lindydonna** [comment]
Just saw this issue myself. Let's just change the storyboard to say "Azure Mobile Apps" so it doesn't need the replacement.

**Comment by lindydonna** [comment]
Assigning to @jwallra per Paul.
