### ISSUE TITLE
Nuget package references mismatch what the Mobile client requires

### ISSUE THREAD

**Issue by gb92** [Azure/azure-mobile-apps-quickstarts#24]
External Nuget package references were updated with Microsoft.Azure.Mobile.Client 2.0.1 but have not been updated in the quickstarts

**Comment by ggailey777** [comment]
Another customer reported this with the Xamarin.Android quickstart download, which I repro'd: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-xamarin-android-get-started/#comment-2629358300

**Comment by adrianhall** [comment]
All the quickstarts now use the ManagedSDKVersion for this.  Downloads show latest version.
