### ISSUE TITLE
iOS app still says "Azure Mobile Services." Change to just Azure

### ISSUE THREAD

**Issue by krisragh** [Azure/azure-mobile-apps-quickstarts#37]
Our iOS app still says "Azure Mobile Services"

I suggest we change this to just "Azure."

I'm guessing we'll change up our branding or marketing again in the future, so it's better for this to be future-proof and just say "Azure," not even "Azure Mobile."

Here is a screenshot:

<img width="434" alt="screen shot 2016-03-09 at 11 21 32 am" src="https://cloud.githubusercontent.com/assets/1638063/13649865/ae4c124a-e5f4-11e5-8d13-8aeb0756b7b0.png">

I think this may affect more than just the iOS client -- it may affect all our clients.

**Comment by adrianhall** [comment]
Hey @jwallra - are the quickstart projects listed in the merge published now?  If so, we can close this issue.

**Comment by krisragh** [comment]
@adrianhall this is still an issue. :( Just tried on two backends: (1) one from 6 months ago, and (2) another I JUST created, just to see if this was fixed on new backends.

**Comment by jwallra** [comment]
I'll follow up on this, I have an idea why this might still be happening.

**Comment by krisragh** [comment]
This is still an issue. I just created a brand new Mobile App backend, and when I downloaded the quickstart iOS project, it STILL says Azure Mobile Services. 

Here's the screenshot: https://www.dropbox.com/s/zojlrt39t679fqn/Screenshot%202016-09-21%2016.13.47.png?dl=0

**Comment by krisragh** [comment]
If you close this issue again, please actually verify this is working in production before doing so? This is the 2nd or 3rd time this issue was closed as fixed, and it's not actually fixed.

**Comment by dhei** [comment]
I verified latest Objective-C quickstart and Swift quickstart are already using "Azure Mobile Apps" term in the UI. Close it.
