### ISSUE TITLE
.NET backend quickstart project fails to run on first publish

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-mobile-apps-quickstarts#47]
I just tried to download, public, and run a new .NET backend quickstart and got this when the new site ran:

> 2016-05-05T16:36:10  PID[12456] Information Request, Method=GET, Url=http://glenga-working.azurewebsites.net/, Message='http://glenga-working.azurewebsites.net/'
> 2016-05-05T16:36:10  PID[12456] Error       Operation=DefaultHttpControllerSelector.SelectController, Exception=System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Data.OData, Version=5.6.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
> File name: 'Microsoft.Data.OData, Version=5.6.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Data.OData, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
> File name: 'Microsoft.Data.OData, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
> 2016-05-05T16:36:10  PID[12456] Information Request, Method=GET, Url=http://glenga-working.azurewebsites.net/, Message='http://glenga-working.azurewebsites.net/'
> 2016-05-05T16:36:10  PID[12456] Error       Operation=DefaultHttpControllerSelector.SelectController, Exception=System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Data.OData, Version=5.6.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
> File name: 'Microsoft.Data.OData, Version=5.6.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Data.OData, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
> File name: 'Microsoft.Data.OData, Version=5.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

After I updated all NuGet packages and republished the site ran OK.
This is a very bad customer experience. The quickstart project needs to come down with a functional set of NuGet packages.

**Comment by adrianhall** [comment]
@ggailey777 Can you remember how you published?  Did you follow the QS instructions?

**Comment by adrianhall** [comment]
I just downloaded the latest QS and tried this out with the prescribed instructions.  Works fine now.  I'm assuming transient error or environmental at this point.
