### ISSUE TITLE
Windows UWP quickstart defaults to ARM solution configuration

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-quickstarts#60]
This will not deploy correctly to local machine. Should be either x86 or x64 (or add a new Any CPU solution configuration)

**Comment by adrianhall** [comment]
Project files don't store the "active" configuration.  A project file has a project group for each configuration contained in the project.  Normally you'll have 4 such groups.  Each group represents a different configuration.  What determines what gets built when you compile is based upon the parameters $(Configuration) and $(Platform).  What the first entry in the project file says is that if no values were set for these parameters then assume debug.  **That is not the same as the active configuration.**  The active configuration is a per-user/per-machine setting that is stored in the .suo file.  The only impact the active configuration has is to determine what parameters get sent to MSBuild when you compile within VS.  For command line builds you have to do the same thing by specifying the configuration and platform to use.  Active configurations do not exist on the command line.

As a result of this analysis, closing this as we cannot distribute a .suo file - it's a binary file and user dependent.  There is, in short, nothing we can do here other than remove the ARM setting.
