### ISSUE TITLE
Windows UWP quickstart tutorial does not include steps to reference SQLiteStore

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-quickstarts#61]

**Comment by lindydonna** [comment]
Does the UWP quickstart have offline sync turned on by default, or are you referring to the commented-out offline sync steps?

**Comment by adrianhall** [comment]
Fixed in latest tutorials: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-windows-store-dotnet-get-started-offline-data/
