### ISSUE TITLE
Xamarin.Forms quickstart should sync on start when offline sync is enabled

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-apps-quickstarts#66]
Customers find it confusing that the Xamarin.Forms implementation of offline sync (which must be enabled manually) does not sync items on startup. We should change the code in OnAppearing to set syncItems to true instead: https://github.com/Azure/azure-mobile-apps-quickstarts/blob/master/client/xamarin.forms/ZUMOAPPNAME/TodoList.xaml.cs#L37.

**Comment by adrianhall** [comment]
Fixed in PR #84
