### ISSUE TITLE
Xamarin.Forms Quickstart and 'Enable offline sync for your Xamarin.Forms mobile app' doc update to v.3.0.1 .NET client SDK 

### ISSUE THREAD

**Issue by dhei** [Azure/azure-mobile-apps-quickstarts#78]
Azure doc link: [Enable offline sync for your Xamarin.Forms mobile app](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-xamarin-forms-get-started-offline-data/)

**Comment by jamesmontemagno** [comment]
Will need some documentation for shared projects and PCLs with Interfaces or static methods of some sort:
http://motzcod.es/post/150988588867/updating-azure-mobile-sqlitestore-to-30

**Comment by adrianhall** [comment]
In progress :-)

**Comment by adrianhall** [comment]
Fixed and merged - awaiting publication (within next 24 hours)
